# Generated by Django 5.1.6 on 2025-02-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="리뷰내용")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="작성일시"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Festival",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="축제명")),
                ("start_month", models.IntegerField()),
                ("middle_month", models.IntegerField()),
                ("end_month", models.IntegerField()),
                ("address", models.CharField(max_length=128, verbose_name="축제주소")),
                ("location", models.CharField(max_length=5, verbose_name="축제지역")),
                ("description", models.TextField(verbose_name="축제소개")),
                (
                    "festival_thumbnail",
                    models.ImageField(
                        blank=True,
                        upload_to="festivals/thumbnail",
                        verbose_name="축제 썸네일",
                    ),
                ),
                ("season", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="HashTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="태그명")),
            ],
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="상호명")),
                ("address", models.CharField(max_length=128, verbose_name="주소")),
                (
                    "call_number",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="전화번호"
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="가게 소개"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarketImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="post", verbose_name="사진")),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
